---
title: "Ingresos"
author: ""Dario Ortiz
---

## Tendencias Temporales por Categoría Principal

A continuación, se presentan las tendencias temporales de los ingresos estatales desglosados por categoría principal para el periodo 2013-2023.

::: {panel-tabset}
### Ingresos Propios

```{r}
#| code-fold: true

graf_temp_5 <- ggplot(ingresos_agregados |> filter(CATEGORIA_PRINCIPAL == "Propios"), 
                    aes(x = ANIO, y = porcentaje_anual, color = ABR_ENT)) +
  geom_line(linewidth = 1.2) +
  geom_point(size = 2) +
  scale_y_continuous(labels = comma) +
  scale_x_continuous(breaks = unique(ingresos_agregados$ANIO)) +
  labs(
    title = "Tendencias Temporales de Ingresos Estatales de la categoría Propios (2013-2023)",
    x = "Año",
    y = "Porcentaje (%)",
    color = "Estado"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom",
    legend.text = element_text(size = 10),
    axis.title.x = element_text(size = 12),
    axis.title.y = element_text(size = 12),
    axis.text.x = element_text(size = 11),
    axis.text.y = element_text(size = 11)
  )

ggplotly(graf_temp_5)

```

### Aportaciones Federales

```{r}
#| code-fold: true

graf_temp_6 <- ggplot(ingresos_agregados |> filter(CATEGORIA_PRINCIPAL == "Aportaciones Federales "), 
                    aes(x = ANIO, y = porcentaje_anual, color = ABR_ENT)) +
  geom_line(linewidth = 1.2) +
  geom_point(size = 2) +
  scale_y_continuous(labels = comma) +
  scale_x_continuous(breaks = unique(ingresos_agregados$ANIO)) +
  labs(
    title = "Tendencias Temporales de Ingresos Estatales de la categoría Aportaciones Federales (2013-2023)",
    x = "Año",
    y = "Porcentaje (%)",
    color = "Estado"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom",
    legend.text = element_text(size = 10),
    axis.title.x = element_text(size = 12),
    axis.title.y = element_text(size = 12),
    axis.text.x = element_text(size = 11),
    axis.text.y = element_text(size = 11)
  )

ggplotly(graf_temp_6)
```


### Participaciones Federales

```{r}
#| code-fold: true

graf_temp_7 <- ggplot(ingresos_agregados |> filter(CATEGORIA_PRINCIPAL == "Participaciones Federales"), 
                    aes(x = ANIO, y = porcentaje_anual, color = ABR_ENT)) +
  geom_line(linewidth = 1.2) +
  geom_point(size = 2) +
  scale_y_continuous(labels = comma) +
  scale_x_continuous(breaks = unique(ingresos_agregados$ANIO)) +
  labs(
    title = "Tendencias Temporales de Ingresos Estatales de la categorías Participaciones Federales (2013-2023)",
    x = "Año",
    y = "Porcentaje (%)",
    color = "Estado"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom",
    legend.text = element_text(size = 10),
    axis.title.x = element_text(size = 12),
    axis.title.y = element_text(size = 12),
    axis.text.x = element_text(size = 11),
    axis.text.y = element_text(size = 11)
  )

ggplotly(graf_temp_7)
```


### Resto de Ingresos

```{r}
#| code-fold: true

graf_temp_8 <- ggplot(ingresos_agregados |> filter(CATEGORIA_PRINCIPAL == "Resto"), 
                    aes(x = ANIO, y = porcentaje_anual, color = ABR_ENT)) +
  geom_line(linewidth = 1.2) +
  geom_point(size = 2) +
  scale_y_continuous(labels = comma) +
  scale_x_continuous(breaks = unique(ingresos_agregados$ANIO)) +
  labs(
    title = "Tendencias Temporales de Ingresos Estatales de la categoría Resto (2013-2023)",
    x = "Año",
    y = "Porcentaje (%)",
    color = "Estado"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 12, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.position = "bottom",
    legend.text = element_text(size = 10),
    axis.title.x = element_text(size = 12),
    axis.title.y = element_text(size = 12),
    axis.text.x = element_text(size = 11),
    axis.text.y = element_text(size = 11)
  )

ggplotly(graf_temp_8)
```
---
